#!/usr/bin/env php
<?php
define('YII_ENV', 'test');
define('YII_DEBUG', true);
// Set path constants
define('CRAFT_BASE_PATH', __DIR__.'/tests/_craft');
define('CRAFT_STORAGE_PATH', __DIR__.'/tests/_craft/storage');
define('CRAFT_TEMPLATES_PATH', __DIR__.'/tests/_craft/templates');
define('CRAFT_CONFIG_PATH', __DIR__.'/tests/_craft/config');
define('CRAFT_VENDOR_PATH', __DIR__.'/vendor');
/**
 * Craft console bootstrap file
 */

// Set path constants
define('CRAFT_BASE_PATH', __DIR__);
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/console.php';
$exitCode = $app->run();
exit($exitCode);
